name: ci

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Build
        run: go build -v ./...

      - name: Install
        run: go install -v

      - name: Show version
        run: apple-dictionary-parser version

      - name: Test
        run: go test -v ./...
